language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd client && npm install && npm test
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
    local_dir: client/build
  on:
    branch: gh-pages